doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'

#        dbname: rank_active
#        host: 127.0.0.1
#        port: 5432
#        user: medvedev
#        password: nuncOmnia113!
#        driver: pdo_pgsql

        dbname: challenger22
        host: 78.46.124.49
        port: 5432
        user: challenger22
        password: v0B4XUN4f
        driver: pdo_pgsql

        # IMPORTANT: You MUST configure your db driver and server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #driver: 'mysql'
        #server_version: '5.7'

        # Only needed for MySQL (ignored otherwise)
        charset: utf8
        default_table_options:
            collate: utf8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true